os:
  - linux
dist: trusty
sudo: required

language: python
python:
  - "2.7"

services:
  - neo4j

before_script:
  - sleep 30

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest -v --cov gff2neo --cov-report=term-missing

after_success:
  coveralls
