os:
  - linux
dist: trusty
sudo: required

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - neo4j

before_script:
  - sleep 30

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest -v