version: '2'
services:
  web:
    build: .
    image: gff2neo
    container_name: gff2neo
    environment:
      DB: db
    depends_on:
      - db
  db:
    restart: always
    image: quay.io/thoba/neo4j:3.2.3
    container_name: gff2neo_db
    environment:
      NEO4J_AUTH: none
    volumes:
      - db_data:/data
    ports:
      - "7687:7687"
      - "7474:7474"
volumes:
  db_data:

#networks:
#  default:
#    external:
#      name: some_network
