{% set version = "0.0.9" %}
{% set sha256 = "6a44c89e6916bad3c990d424eb3c68ea8b325f52e755ac6e621fd4087a6dcfa1" %}
{% set py2neo = "3.1.2" %}

package:
  name: tb2neo
  version: {{ version }}

source:
  url: https://github.com/COMBAT-TB/tb2neo/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0


requirements:
  host:
    - python
    - pip
    - click
    - py2neo {{ py2neo }}
    - tqdm
    - biopython
    - bioservices
    - bcbio-gff
  run:
    - python
    - click
    - py2neo {{ py2neo }}
    - tqdm
    - biopython
    - bioservices
    - bcbio-gff

test:
  imports:
    - tb2neo
  commands:
    - tb2neo |& grep tb2neo

about:
  home: https://github.com/COMBAT-TB/tb2neo
  license_file: LICENSE
  summary: 'Parses M.tuberculosis annotation (GFF file) and builds a Neo4j graph database storing the annotated features.'
  dev_url: https://github.com/COMBAT-TB/tb2neo
